import { QUESTIONS } from './questions.js';

const COURSES = {
  length:{name:'길이 놀이터',emoji:'🎀',units:'cm · m',desc:'리본과 국수로 길이를 쏙!',title:'길이를 재는 마법',intro:'cm는 작은 길이, m는 더 긴 길이를 잴 때 써요.',rule:'100 cm = 1 m',total:100,unit:'cm',factor:100,big:'m',label:'남은 리본'},
  weight:{name:'무게 주방',emoji:'🍓',units:'g · kg',desc:'과일을 나누면 얼마나?',title:'무게를 재는 마법',intro:'g는 가벼운 무게, kg는 더 무거운 무게를 잴 때 써요.',rule:'1,000 g = 1 kg',total:1000,unit:'g',factor:1000,big:'kg',label:'남은 딸기'},
  distance:{name:'숲속 산책',emoji:'🌳',units:'m · km',desc:'요정과 함께 한 걸음씩',title:'먼 길을 재는 마법',intro:'m를 1,000개 모으면 km가 돼요. 멀리 가는 길에 써요.',rule:'1,000 m = 1 km',total:1000,unit:'m',factor:1000,big:'km',label:'앞으로 갈 길'},
  mix:{name:'퍼센트 마법',emoji:'🪄',units:'단위 × %',desc:'길이와 무게에 %를 톡!',title:'100조각의 마법',intro:'%는 전체를 똑같이 100조각으로 나누었을 때 몇 조각인지 알려줘요.',rule:'전체 = 100% · 절반 = 50%',total:100,unit:'cm',factor:100,big:'m',label:'남은 리본'}
};
const AWARDS=[{score:30,emoji:'🌱',name:'호기심 새싹'},{score:80,emoji:'🌸',name:'발견의 꽃'},{score:150,emoji:'🦋',name:'반짝 나비'},{score:240,emoji:'👑',name:'단위 요정'}];
const KEY='fairy-math-garden-v1';
const app=document.querySelector('#app');
const fmt=n=>Number(n.toFixed(4)).toLocaleString('ko-KR',{maximumFractionDigits:4});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const freshProfile=()=>({level:1,records:{},sessions:0,active:null,paused:{}});
const blank=()=>({version:1,selected:'tae',profiles:{tae:freshProfile(),se:freshProfile()}});
const names={tae:'태희',se:'세희'};
let storageOK=true, state=blank(), view='home', lessonCourse='length', modal=null, previousFocus=null;
function sanitize(raw){
  if(!raw||raw.version!==1||!raw.profiles)throw new Error('지원하지 않는 기록 파일이에요.');
  const next=blank();next.selected=['tae','se'].includes(raw.selected)?raw.selected:'tae';
  for(const id of ['tae','se']){
    const source=raw.profiles[id];if(!source||typeof source!=='object')throw new Error('아이별 기록을 찾을 수 없어요.');
    const p=next.profiles[id];p.level=source.level===2?2:1;p.sessions=Math.max(0,Math.min(100000,Math.floor(Number(source.sessions)||0)));
    for(const q of QUESTIONS){const r=source.records?.[q.id];if(r&&[2,10].includes(r.best))p.records[q.id]={best:r.best,seen:Math.max(1,Math.min(100000,Math.floor(Number(r.seen)||1)))};}
    const s=source.active;
    if(s&&COURSES[s.course]&&[1,2].includes(s.level)&&Array.isArray(s.ids)&&s.ids.length===5&&new Set(s.ids).size===5&&s.ids.every(id=>QUESTIONS.some(q=>q.id===id&&q.course===s.course&&q.level===s.level))&&Number.isInteger(s.index)&&s.index>=0&&s.index<=5&&Array.isArray(s.answers)){
      const answers=s.answers.slice(0,5).filter((a,i)=>a&&a.id===s.ids[i]&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<3&&Number.isInteger(a.earned)&&a.earned>=0&&a.earned<=10).map(a=>({...a,correct:a.choice===QUESTIONS.find(q=>q.id===a.id).answer}));
      if(answers.length>=s.index&&answers.length<=Math.min(s.index+1,5))p.active={course:s.course,level:s.level,ids:[...s.ids],index:s.index,answers,finished:s.finished===true&&s.index===5};
    }
  }
  for(const id of ['tae','se']){const paused=raw.profiles[id].paused;if(paused&&typeof paused==='object')for(const [key,session] of Object.entries(paused)){if(!/^(length|weight|distance|mix)-[12]$/.test(key))continue;const temp=blank();temp.profiles[id].active=session;const valid=sanitize(temp).profiles[id].active;if(valid&&!valid.finished&&key===valid.course+'-'+valid.level)next.profiles[id].paused[key]=valid;}}
  return next;
}
try{const raw=localStorage.getItem(KEY);if(raw)state=sanitize(JSON.parse(raw));}catch{storageOK=false;}
// Shared learner choice from the family launchpad; existing scores keep their original key.
try{const shared=JSON.parse(localStorage.getItem('sparkle-learner-v1'));if(shared&&Object.hasOwn(names,shared.id))state.selected=shared.id;}catch{}
const profile=()=>state.profiles[state.selected];
const score=(p=profile())=>Object.values(p.records).reduce((sum,r)=>sum+r.best,0);
function mergeRecords(incoming){for(const id of ['tae','se']){const p=state.profiles[id],src=incoming.profiles[id];for(const [qid,r] of Object.entries(src.records)){const old=p.records[qid];p.records[qid]={best:Math.max(old?.best||0,r.best),seen:Math.max(old?.seen||0,r.seen)};}p.sessions=Math.max(p.sessions,src.sessions);}}
function save(){try{const stored=localStorage.getItem(KEY);if(stored){try{mergeRecords(sanitize(JSON.parse(stored)));}catch{}}localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
function stopSpeech(){if('speechSynthesis'in window)window.speechSynthesis.cancel();}
function go(next){stopSpeech();view=next;render();window.scrollTo({top:0,behavior:'instant'});document.querySelector('main h1,main h2')?.focus({preventScroll:true});}
function header(){return `<header class="header"><button class="brand" data-action="home" aria-label="반짝 단위 정원 처음으로"><b class="brand-mark" aria-hidden="true">✦</b><span><small>TAEHEE & SEHEE</small>반짝! 단위 정원</span></button><nav class="nav" aria-label="주 메뉴"><a class="hub-link" href="../sparkle-learning-hub/">배움터</a><button data-action="home" class="${view!=='collection'?'active':''}" ${view!=='collection'?'aria-current="page"':''}>놀이하기</button><button data-action="collection" class="${view==='collection'?'active':''}" ${view==='collection'?'aria-current="page"':''}>별 보관함</button></nav><div class="userbar"><span class="score-pill" aria-label="누적 별 ${score()}개">⭐ ${score()}</span><button class="profile-button" data-action="profiles" aria-label="아이 바꾸기, 현재 ${names[state.selected]}"><span class="avatar" aria-hidden="true">${state.selected==='tae'?'🌸':'🌙'}</span>${names[state.selected]}<span class="chevron" aria-hidden="true">⌄</span></button></div></header>`;}
function footer(){return `<footer class="footer"><span>작은 발견을 모아, 반짝반짝 ✦</span><button data-action="parents">보호자 안내</button></footer>`;}
function nextAward(){return AWARDS.find(a=>a.score>score());}
function home(){const p=profile(),next=nextAward();return `${p.active&&!p.active.finished?`<div class="resume"><span>${COURSES[p.active.course].emoji} 하던 놀이가 있어요</span><button data-action="resume">이어서 풀기</button></div>`:''}<section class="welcome"><div class="welcome-copy"><div class="eyebrow"><span class="tiny-tag">태희와 세희의 작은 배움터</span></div><h1 tabindex="-1">${names[state.selected]}야, 반가워!<br><em>어떤 마법</em>을 배울까?</h1><p>길이도, 무게도, 퍼센트도<br>요정 친구와 놀면서 쏙!</p></div><img class="welcome-art" src="./assets/fairy-companions.webp" alt="분홍 별 요정과 보라 달 요정" width="315" height="240"></section><div class="section-head"><div class="section-title"><h2>오늘의 놀이</h2><span>한 번에 5문제</span></div><div class="segmented" aria-label="난이도"><button data-action="level" data-level="1" aria-pressed="${p.level===1}">🌱 새싹</button><button data-action="level" data-level="2" aria-pressed="${p.level===2}">✨ 반짝</button></div></div><div class="course-grid">${Object.entries(COURSES).map(([id,c])=>`<button class="course ${id}" data-action="lesson" data-course="${id}"><span class="course-icon" aria-hidden="true">${c.emoji}</span><span class="units">${c.units}</span><h3>${c.name}</h3><p>${c.desc}</p><span class="play-label">놀러 가기 <span class="play-dot" aria-hidden="true">▶</span></span></button>`).join('')}</div><p class="level-note">${p.level===1?'새싹은 전체와 절반부터 차근차근 배워요.':'반짝은 10%, 25%, 75%처럼 여러 비율을 만나요.'}</p><section class="reward-preview"><span class="gift-icon" aria-hidden="true">${next?next.emoji:'👑'}</span><div class="reward-copy"><h3>${next?`다음 선물은 ‘${next.name}’`:'단위 요정의 정원이 반짝여요!'}</h3><p>${next?`별 ${next.score-score()}개를 더 모으면 만날 수 있어요.`:'새로운 문제와 복습으로 발견을 이어 가요.'}</p><div class="reward-track" role="progressbar" aria-label="다음 선물까지 누적 별" aria-valuenow="${Math.min(score(),next?.score||240)}" aria-valuemin="0" aria-valuemax="${next?.score||240}"><span style="width:${Math.min(100,score()/(next?.score||240)*100)}%"></span></div></div><button class="text-button" data-action="collection">내 별 보러 가기</button></section>`;}
function bar(percent,{grid=false}={}){const count=grid?100:20;return `<div class="${grid?'grid100':'bar'}" role="img" aria-label="전체 중 ${percent}%가 남아 있는 그림">${Array.from({length:count},(_,i)=>`<span class="${i<count*percent/100?'filled':''}"></span>`).join('')}</div>`;}
function lesson(){const c=COURSES[lessonCourse];return `<div class="activity"><div class="activity-top"><button class="back" data-action="home">정원으로</button><span class="activity-label">${c.name} · 먼저 만져 봐요</span></div><section class="card"><div class="lesson-title"><div class="big-emoji" aria-hidden="true">${c.emoji}</div><h1 tabindex="-1">${c.title}</h1><p>${c.intro}</p></div><div class="equivalence">${c.rule}</div><div class="concept-controls"><div class="concept-label"><label for="portion">${lessonCourse==='mix'?'100cm 리본, 남은 만큼!':'남은 만큼 움직여 봐!'}</label><span id="portion-label">50%</span></div><div id="concept-picture">${bar(50,{grid:lessonCourse==='mix'})}</div><input id="portion" class="range" type="range" min="0" max="100" step="25" value="50" aria-valuetext="50퍼센트, 절반"><div class="range-labels"><span>하나도 없음</span><span>절반</span><span>전체</span></div><div class="concept-result" aria-live="polite" id="concept-result">${conceptResult(50)}</div></div><button class="primary" data-action="start" data-course="${lessonCourse}">${(profile().active&&!profile().active.finished&&profile().active.course===lessonCourse&&profile().active.level===profile().level)||profile().paused[lessonCourse+'-'+profile().level]?'하던 이야기 이어 풀기':'이야기 5문제 풀기'}</button><p class="helper">천천히 생각해도 괜찮아. 시간 제한은 없어!</p></section></div>`;}
function conceptResult(percent){const c=COURSES[lessonCourse],v=c.total*percent/100;const detail={0:'0%는 하나도 남지 않은 거예요.',25:'25%는 똑같이 4개로 나눈 것 중 1개예요.',50:'0.5는 1의 절반이에요. 50%도 절반이에요.',75:'75%는 똑같이 4개로 나눈 것 중 3개예요.',100:'100%는 처음의 전체가 그대로 있는 거예요.'};return `<strong>${fmt(v)} ${c.unit} = ${fmt(v/c.factor)} ${c.big}</strong><p>${detail[percent]}</p>`;}
function usedLabel(q){if(q.convertUnit==='km')return '이미 지나온 길';if(/이었|완성/.test(q.story))return '이미 만든 부분';if(/먹/.test(q.story))return '이미 먹은 부분';if(/구웠|굽/.test(q.story))return '이미 구운 부분';if(/나누어|주었/.test(q.story))return '나누어 준 부분';return '이미 쓴 부분';}
function quiz(){const s=profile().active;if(!s)return home();if(s.index===5)return result();const q=QUESTIONS.find(q=>q.id===s.ids[s.index]),a=s.answers[s.index];return `<div class="activity"><div class="activity-top"><button class="back" data-action="home">잠깐 쉬기</button><span class="activity-label">${COURSES[s.course].name} · ${s.level===1?'새싹':'반짝'}</span></div><div class="progress-row"><span>${s.index+1} / 5</span><div class="steps" aria-label="다섯 문제 중 ${s.index+1}번째">${Array.from({length:5},(_,i)=>`<span class="step ${i<s.index?'done':i===s.index?'current':''}"></span>`).join('')}</div><span>⭐ ${s.answers.reduce((n,a)=>n+a.earned,0)}</span></div><section class="card"><div class="story-heading"><div class="story-emoji" aria-hidden="true">${q.emoji}</div><div><p class="story-tag">생각이 반짝이는 이야기</p><h1 tabindex="-1">${esc(q.title)}</h1></div>${'speechSynthesis'in window?'<button class="listen" data-action="listen" aria-label="문제 소리 내어 읽기">🔊</button>':''}</div><p class="story">${esc(q.story)}</p><div class="visual"><div class="visual-meta"><span>처음 전체</span><span>${fmt(q.total)} ${q.baseUnit}</span></div>${bar(q.percent)}<div class="visual-meta bottom"><span class="remaining">■ ${esc(q.visualLabel)}</span><span>□ ${esc(usedLabel(q))}</span></div></div><h2 class="prompt">${esc(q.prompt)}</h2><div class="choices" aria-label="답 고르기">${q.choices.map((choice,i)=>`<button class="choice ${a?(i===q.answer?'correct':i===a.choice?'wrong':''):''}" data-action="answer" data-choice="${i}" ${a?'disabled':''}><span class="choice-num">${a&&i===q.answer?'✓':i+1}</span><span>${esc(choice).replace(/ · /g,' <span aria-hidden="true">·</span> ')}</span></button>`).join('')}</div>${a?`<section class="feedback ${a.correct?'':'learn'}" id="feedback" tabindex="-1" aria-label="정답과 해설"><h2><span>${a.correct?'✨ 맞아, 잘 찾았어!':'🌱 같이 알아보자!'}</span><span class="earned">${a.earned?`⭐ +${a.earned}`:'복습 완료'}</span></h2><div class="answer-visual">${esc(q.choices[q.answer])}</div>${q.explain.map(line=>`<p>${esc(line)}</p>`).join('')}<p class="answerline">${esc(q.visualLabel)}: 전체의 ${q.percent}%</p><button class="primary" data-action="next">${s.index===4?'오늘 모은 별 보기':'다음 이야기'}</button></section>`:''}</section>${!a?'<p class="quiz-note">그림을 보고, 마음속으로 나누어 봐요.</p>':''}</div>`;}
function result(){const s=profile().active;if(!s)return home();const correct=s.answers.filter(a=>a.correct).length,earned=s.answers.reduce((n,a)=>n+a.earned,0),reflection={length:'집에서 1m쯤 되는 물건을 함께 찾아볼까?',weight:'1kg 과일의 절반은 왜 500g일까?',distance:'1km를 절반 걸으면 몇 m가 남을까?',mix:'크기가 다른 두 리본도 절반은 둘 다 50%일까?'}[s.course];return `<div class="activity"><section class="card result"><div class="result-icon sparkle" aria-hidden="true">${correct===5?'🌟':'🌸'}</div><h1 tabindex="-1">${names[state.selected]}의 생각이 자랐어!</h1><p class="result-sub">다섯 이야기를 끝까지 만났네.<br>${correct===5?'새로운 발견이 반짝반짝!':'함께 배운 문제도 소중한 발견이야.'}</p><div class="result-stats"><div class="stat"><strong>⭐ +${earned}</strong><span>이번에 모은 별</span></div><div class="stat"><strong>${correct} / 5</strong><span>스스로 찾은 답</span></div></div><div class="reflection"><small>엄마 아빠에게 들려줘</small>${reflection}</div><button class="primary" data-action="home">정원으로 돌아가기</button><button class="text-button" data-action="collection">내 별 보러 가기</button></section></div>`;}
function collection(){const p=profile(),mastered=Object.values(p.records).filter(r=>r.best===10).length;return `<section class="collection-head"><div class="eyebrow">${names[state.selected]}의 반짝이는 발자국</div><h1 tabindex="-1">별 ${score()}개, 발견은 차곡차곡!</h1><p>하나씩 알아갈 때마다 정원이 자라요.</p></section><div class="award-grid">${AWARDS.map(a=>`<article class="award ${score()<a.score?'locked':''}"><div class="award-icon" aria-hidden="true">${a.emoji}</div><h3>${a.name}</h3><p>${score()>=a.score?'✨ 나의 정원에 도착!':`별 ${a.score}개에 만나요`}</p></article>`).join('')}</div><section class="mastery"><h2>내가 찾은 이야기</h2>${Object.entries(COURSES).map(([id,c])=>`<div class="mastery-row"><span>${c.emoji} ${c.name}</span><span>${QUESTIONS.filter(q=>q.course===id&&p.records[q.id]?.best===10).length} / ${QUESTIONS.filter(q=>q.course===id).length}</span></div>`).join('')}<p class="saved-note">총 ${mastered}개의 답을 스스로 찾았어요.<br>별과 학습 기록은 이 기기의 브라우저에 저장돼요.</p></section>`;}
function render(){const content=({home,lesson,quiz,collection,result}[view]||home)();app.innerHTML=`${header()}<main id="main">${!storageOK?'<div class="status-message" role="status">지금은 기록을 저장할 수 없어요. 보호자 안내에서 기록을 내보내 주세요.</div>':''}${content}</main>${footer()}`;}
function start(course){if(!COURSES[course])throw new Error('알 수 없는 놀이예요.');const p=profile();const key=course+'-'+p.level;let resume=null;if(p.active&&!p.active.finished){if(p.active.course===course&&p.active.level===p.level)resume=p.active;else p.paused[p.active.course+'-'+p.active.level]=p.active;}resume=resume||p.paused[key];if(resume){p.active=resume;delete p.paused[key];save();go('quiz');return {course,count:5,resumed:true};}const pool=QUESTIONS.filter(q=>q.course===course&&q.level===p.level).map(q=>({q,weight:(p.records[q.id]?.best||0)*10+(p.records[q.id]?.seen||0)+Math.random()})).sort((a,b)=>a.weight-b.weight).slice(0,5).map(x=>x.q.id);p.active={course,level:p.level,ids:pool,index:0,answers:[],finished:false};save();go('quiz');return {course,count:pool.length};}
function answer(choice){const p=profile(),s=p.active;if(view!=='quiz'||!s||s.index>=5||s.answers[s.index])return false;if(!Number.isInteger(choice)||choice<0||choice>2)throw new Error('답을 하나 골라 주세요.');const q=QUESTIONS.find(q=>q.id===s.ids[s.index]),correct=choice===q.answer,old=p.records[q.id]?.best||0,best=Math.max(old,correct?10:2),earned=best-old;p.records[q.id]={best,seen:(p.records[q.id]?.seen||0)+1};s.answers.push({id:q.id,choice,correct,earned});save();render();document.querySelector('#feedback')?.focus({preventScroll:true});document.querySelector('#feedback')?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.querySelector('#announcer').textContent=correct?'맞았어요. 정답 해설을 확인해요.':'함께 알아봐요. 정답 해설을 확인해요.';return true;}
function next(){const p=profile(),s=p.active;if(!s||s.finished||!s.answers[s.index])return;s.index++;if(s.index===5){s.finished=true;p.sessions++;}save();go(s.finished?'result':'quiz');}
function selectProfile(id){if(!names[id])throw new Error('아이를 선택해 주세요.');state.selected=id;try{localStorage.setItem('sparkle-learner-v1',JSON.stringify({id}));}catch{}save();closeModal();go('home');}
function openModal(type){modal=type;previousFocus=document.activeElement;const wrap=document.createElement('div');wrap.className='overlay';wrap.id='modal';wrap.innerHTML=`<section role="dialog" aria-modal="true" aria-labelledby="dialog-title" class="dialog"><div class="dialog-top"><h2 id="dialog-title">${type==='profiles'?'누구의 정원으로 갈까?':'보호자 안내'}</h2><button class="close" data-action="close" aria-label="닫기">×</button></div>${type==='profiles'?`<div class="profiles">${Object.entries(names).map(([id,name])=>`<button class="profile-choice" data-action="select-profile" data-profile="${id}"><span class="avatar" aria-hidden="true">${id==='tae'?'🌸':'🌙'}</span><br>${name}<small>⭐ ${score(state.profiles[id])}개</small></button>`).join('')}</div>`:`<div class="parent-copy"><p><strong>새싹</strong>은 전체·절반과 단위 변환을, <strong>반짝</strong>은 다양한 백분율과 단위를 함께 배웁니다. 0.5는 절반으로 먼저 소개합니다.</p><p>총 48문항이며 한 번에 5개씩 만납니다. 아직 익히지 않은 문제를 우선 제시합니다. 실제 물건을 재거나 아이가 풀이를 말로 설명하도록 함께해 주세요.</p><p><strong>별 모으기</strong><br>새 문제 정답은 10개, 해설과 함께 배우면 2개입니다. 나중에 스스로 맞히면 8개를 더 받아요. 같은 문제의 별은 최대 10개여서 반복 클릭으로 늘어나지 않아요.</p><p><strong>기록 저장</strong><br>현재 기기의 이 브라우저에 태희·세희 기록을 따로 저장합니다. 다른 기기로 자동 동기화되지 않으며, 방문 기록 삭제나 비공개 모드 종료 시 사라질 수 있습니다. 내보내기 파일로 기록을 옮길 수 있습니다.</p><div class="parent-actions"><button class="secondary" data-action="export">기록 내보내기</button><button class="secondary" data-action="import">기록 가져오기</button></div><input id="import-file" type="file" accept="application/json,.json" hidden><p id="import-status" role="status" style="margin-top:12px"></p><p>문제 읽어주기는 기기의 한국어 음성을 사용합니다. 음성이 없으면 작동하지 않을 수 있어요.</p></div>`}</section>`;document.body.append(wrap);app.inert=true;document.body.style.overflow='hidden';wrap.querySelector('button').focus();}
function closeModal(){document.querySelector('#modal')?.remove();app.inert=false;document.body.style.overflow='';modal=null;previousFocus?.focus();}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fairy-garden-records-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function mergeData(imported){for(const id of ['tae','se']){const p=state.profiles[id],src=imported.profiles[id];for(const [qid,r]of Object.entries(src.records)){const old=p.records[qid];p.records[qid]={best:Math.max(old?.best||0,r.best),seen:Math.max(old?.seen||0,r.seen)};}p.sessions=Math.max(p.sessions,src.sessions);}save();render();}
function listen(){const s=profile().active,q=s&&QUESTIONS.find(q=>q.id===s.ids[s.index]);if(!q||!('speechSynthesis'in window))return;stopSpeech();const u=new SpeechSynthesisUtterance(`${q.story} ${q.prompt}`);u.lang='ko-KR';u.rate=.85;u.onerror=()=>{document.querySelector('#announcer').textContent='이 기기에서 한국어 읽어주기를 사용할 수 없어요.'};window.speechSynthesis.speak(u);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;switch(action){case'home':go('home');break;case'collection':go('collection');break;case'level':profile().level=Number(b.dataset.level);save();render();break;case'lesson':lessonCourse=b.dataset.course;go('lesson');break;case'start':start(b.dataset.course);break;case'answer':answer(Number(b.dataset.choice));break;case'next':next();break;case'resume':go(profile().active?.finished?'result':'quiz');break;case'profiles':openModal('profiles');break;case'parents':openModal('parents');break;case'close':closeModal();break;case'select-profile':selectProfile(b.dataset.profile);break;case'listen':listen();break;case'export':exportData();break;case'import':document.querySelector('#import-file').click();break;}});
document.addEventListener('input',e=>{if(e.target.id!=='portion')return;const v=Number(e.target.value);document.querySelector('#portion-label').textContent=`${v}%`;document.querySelector('#concept-picture').innerHTML=bar(v,{grid:lessonCourse==='mix'});document.querySelector('#concept-result').innerHTML=conceptResult(v);e.target.setAttribute('aria-valuetext',`${v}퍼센트`);});
document.addEventListener('change',async e=>{if(e.target.id!=='import-file'||!e.target.files[0])return;const status=document.querySelector('#import-status');try{if(e.target.files[0].size>1000000)throw new Error('파일이 너무 커요. 내보낸 기록 파일을 선택해 주세요.');const imported=sanitize(JSON.parse(await e.target.files[0].text()));mergeData(imported);app.inert=true;status.textContent='기록을 합쳤어요. 기존 별과 기록도 지켰어요.';}catch(error){status.textContent=`가져오지 못했어요. ${error instanceof SyntaxError?'올바른 기록 JSON 파일을 선택해 주세요.':error.message}`;}e.target.value='';});
document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const focusable=[...document.querySelector('#modal').querySelectorAll('button,input:not([hidden]),a[href]')].filter(x=>!x.disabled),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
// Cross-tab edits merge best results without dropping the active tab's session.
window.addEventListener('storage',e=>{if(e.key==='sparkle-learner-v1'){try{const shared=JSON.parse(e.newValue);if(shared&&Object.hasOwn(names,shared.id)){if(modal)closeModal();state.selected=shared.id;go('home');}}catch{}return;}if(e.key!==KEY||!e.newValue)return;try{const incoming=sanitize(JSON.parse(e.newValue));for(const id of ['tae','se']){const p=state.profiles[id],src=incoming.profiles[id];for(const [qid,r]of Object.entries(src.records)){const old=p.records[qid];p.records[qid]={best:Math.max(old?.best||0,r.best),seen:Math.max(old?.seen||0,r.seen)};}p.sessions=Math.max(p.sessions,src.sessions);}const differs=['tae','se'].some(id=>JSON.stringify(state.profiles[id].records)!==JSON.stringify(incoming.profiles[id].records)||state.profiles[id].sessions!==incoming.profiles[id].sessions);if(differs)save();if(!modal)render();}catch{}});
render();
// Progressive WebMCP enhancement; unsupported browsers use the normal interface.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_learning_progress',description:'현재 아이의 누적 별과 코스별 완료 기록을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({profile:names[state.selected],stars:score(),mastered:Object.values(profile().records).filter(r=>r.best===10).length,view})});
 register({name:'open_learning_concept',description:'선택한 놀이의 개념 화면을 엽니다. 문제에 답하거나 점수를 주지 않습니다.',inputSchema:{type:'object',properties:{course:{type:'string',enum:Object.keys(COURSES)}},required:['course'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!COURSES[input.course]||Object.keys(input).some(k=>k!=='course'))throw new Error('유효한 course가 필요합니다.');lessonCourse=input.course;go('lesson');return{view,course:lessonCourse};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
